### ISSUE TITLE
Rademacher vectors biased

### ISSUE THREAD

**Issue by peekxc** [ameli/imate#4]
I believe there is a bug that causes the rademacher vectors to be biased and thus the trace estimators as well. The effect becomes a small constant as the matrices get larger (on the order of $\sim O(n - 64 \lfloor n / 64 \rfloor)$, but for smaller matrices it's quite noticeable. 

In particular, I was running some statistical tests on the RNG's used by the package, I noticed that randomly-generated rademacher vectors of size `100` had sums varying far from 0. Here's a picture I screen-grabbed, with the red-line showing the cumulative averages: 

<img width="431" alt="Screen Shot 2023-09-06 at 11 31 15 AM" src="https://github.com/ameli/imate/assets/11429028/6c90c5bf-c301-4d5d-af2d-f6b1c09587c3">

In contrast, the same code that uses `np.random.choice([-1.0,+1.0], size=100)` 5000 times yields expected behavior:

<img width="663" alt="Screen Shot 2023-09-06 at 11 31 24 AM" src="https://github.com/ameli/imate/assets/11429028/e1845843-308d-428d-a1cc-d12618be05fe">

Upon further investigation, I found the culprit seems to be [these lines](https://github.com/ameli/imate/blob/de867f131a4cda7d60a68bf0558e896fae89d776/imate/_random_generator/random_array_generator.cpp#L144-L159). Essentially, you have two loops, which looks like (simplified): 

```cpp
for (int i=0; i < int(array_size/num_bits); ++i) {                         // i indexes the blocks 
    uint64_t bits = rng.next(thread_id);                                   // bits has size 64 
    for (int j=0; j < num_bits; ++j){                                      // 0 <= j < 64, j indexes *relative* position
        array[i*num_bits + j] = (bits & ( uint64_t(1) << j)) ? 1.0 : -1.0; 
    }
}
uint64_t bits = rng.next(thread_id);
for (int j = (array_size/num_bits) * num_bits; j < array_size; ++j) { // <-- x <= j < array_size, j indexes global position  
    array[j] = (bits & ( uint64_t(1) << j)) ? 1.0 : -1.0;             // <-- LHS is fine, shift is wrong, as j could be larger than 64 bits! 
}
```

The second for loop uses `j` to index the global position and the bit shift. This can't be right, because `j` could be larger than 64 here. Indeed, in my example above where the `n=100`, this code randomly generates {-1, +1} for the first 64 entries but keeps the remaining 100-64 elements fixed to -1, explaining the bias. 

The correction should be something like (using modern c++ for succinctness): 

```cpp
std::bitset< 64 > ubits { rng.next(thread_id) };
for (int j = int(array_size/num_bits) * num_bits, i = int(0); j < array_size; ++j, ++i){  // use j for global index for LHS, i for relative index 
    array[j] = ubits[i] ? 1.0 : -1.0; // <-- 0<= i < 64 so RHS is fine
}
``` 
I verified this indeed fixes the bias after implementing these changes and exposing said generators in [a port of this code to separate package](https://github.com/peekxc/pyimate) (very much so work in progress):

<img width="675" alt="Screen Shot 2023-09-06 at 8 58 08 PM" src="https://github.com/ameli/imate/assets/11429028/e3042595-0a89-4743-a9cc-dbf6fa31763b">

**Comment by ameli** [comment]
Appreciate the bug report and your verification analysis. The issue has been resolved.
