### ISSUE TITLE
Imate for Apple M1 architecture

### ISSUE THREAD

**Issue by schenkch** [ameli/imate#5]
I have been trying to install imate as one of the requirements of another package and have not been able to build the wheels for it on my Apple Silicon M1. 
I received the following error:
Building wheels for collected packages: imate
  Building wheel for imate (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for imate (pyproject.toml) did not run successfully.
  │ exit code: 1

Could you build it for me, please?

**Comment by ameli** [comment]
Thanks for flagging this! I've added arm64 wheels, now available via pip. Since I don't have an M1 machine to test them, I would appreciate it if you could report any library-dependency problems you encounter. Also, ensure [OpenMP](https://ameli.github.io/imate/install/dependencies.html#openmp-required) is installed and doesn't conflict with [MKL](https://ameli.github.io/imate/install/troubleshooting.html#issue-of-initializing-libomp), as these can be typical issues on MacOS.

**Comment by schenkch** [comment]
Thanks a lot. I tried installing and importing it but got the following errors. I set it up in a virtual environment but installed OpenMP via homebrew before. Do you have any idea how to resolve this?
![Screenshot 2023-12-05 at 09 19 44](https://github.com/ameli/imate/assets/22678899/e46388a1-4d5b-4318-8f6d-79bb31273f3e)

**Comment by ameli** [comment]
The message indicates the package cannot find openmp. You may try reinstalling it via ``brew reinstall libomp`` or ``brew reinstall llvm libomp`` or ``brew reintall gcc`` (where ``gcc`` also installs openmp).

If that did not work, try installing openmp via compilers that ``conda`` offers. For example ``conda install llvm``, or ``conda install gcc`` or ``conda install libgcc``.

Alternatively, OpenMP might have been installed in a non-standard location where it cannot be found by the Python package. You can find its location with:

    brew list libomp

This might show paths like (might be different on your machine):

    /opt/homebrew/Cellar/libomp/14.0.5/include/ (3 files)
    /opt/homebrew/Cellar/libomp/14.0.5/lib/libomp.dylib
    /opt/homebrew/Cellar/libomp/14.0.5/lib/libomp.a

If this is the case, you can create symbolic links (with ``ln``) from the files in the listed locations to their standard counterparts as shown below:

    ln -sf /opt/homebrew/Cellar/libomp/14.0.5/include/omp.h        /usr/local/include/omp.h
    ln -sf /opt/homebrew/Cellar/libomp/14.0.5/include/ompt.h       /usr/local/include/ompt.h
    ln -sf /opt/homebrew/Cellar/libomp/14.0.5/include/omp-tools.h  /usr/local/include/omp-tools.h
    ln -sf /opt/homebrew/Cellar/libomp/14.0.5/lib/libomp.a         /usr/local/lib/libomp.a
    ln -sf /opt/homebrew/Cellar/libomp/14.0.5/lib/libomp.dylib     /usr/local/lib/libomp.dylib

You may replace the paths ``/opt/homebrew/Cellar/libomp/14.0.5/...`` in the above according to where openmp is originally installed on your machine.

**Comment by schenkch** [comment]
Thank you for all the suggestions. I tried all that but still get the same errors. If you have any other idea, please let me know.

**Comment by ameli** [comment]
I've built new wheels natively on an M1 machine. Could you please uninstall any older versions and try installing the latest one with ``python -m pip install --upgrade imate``?

**Comment by schenkch** [comment]
Great, thank you so much. It looks like now it works.

**Comment by ameli** [comment]
Glad to hear it worked. I'll close this thread, but please don't hesitate to reopen it if any issues arise.
